import express from 'express';
import { Pool } from 'pg';
import crypto from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import nodemailer from 'nodemailer';

const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dbUrl = process.env.DATABASE_URL;
const pool = dbUrl ? new Pool({ connectionString: dbUrl, ssl: !dbUrl.includes('localhost') ? { rejectUnauthorized: false } : undefined, max: 5 }) : null;
const q = (s,p=[]) => pool.query(s,p);
const one = async (s,p=[]) => (await q(s,p)).rows[0] || null;
const sha = v => crypto.createHash('sha256').update(String(v)).digest('hex');
const makeHash = (password,salt=crypto.randomBytes(16).toString('hex')) => `${salt}:${sha(salt+password)}`;
const verify = (password,value) => { const [salt,h] = String(value||'').split(':'); return !!salt && h === sha(salt+password); };
const smtp = process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS ? nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE||'true')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}) : null;
const adminMail = process.env.ADMIN_EMAIL || process.env.SMTP_TO || process.env.SMTP_USER || '';
async function sendNewRepairEmail(repair,device){if(!smtp||!adminMail)return {sent:false,error:'ยังไม่ได้ตั้งค่า SMTP หรือ ADMIN_EMAIL'};const dateOnly=v=>{const s=String(v??'');const m=s.match(/^(\d{4}-\d{2}-\d{2})/);return m?m[1].split('-').reverse().join('/'):s};try{await smtp.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:adminMail,subject:`[JMW Chromebook] มีการแจ้งซ่อมใหม่ #${repair.id}`,text:`มีการแจ้งซ่อม Chromebook ใหม่\n\nเลขที่แจ้งซ่อม: #${repair.id}\nวันที่แจ้ง: ${dateOnly(repair.opened_at)}\nผู้แจ้ง: ${repair.reporter_name}\nอีเมล: ${repair.reporter_email||'-'}\nเครื่อง S/N: ${device.serial_number}\nรหัสเครื่อง: ${device.asset_code}\nอาการ: ${repair.issue}\nรายละเอียด: ${repair.details||'-'}\n\nเข้าสู่ระบบ Admin เพื่อดำเนินการต่อ`});return {sent:true}}catch(e){console.error('[SMTP NEW REPAIR]',e);return {sent:false,error:e.message||'ส่งอีเมลไม่สำเร็จ'}}}
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
let initialized;async function init(){if(initialized)return initialized;initialized=(async()=>{if(!pool)throw new Error('DATABASE_URL is not configured in Vercel');await q(`CREATE TABLE IF NOT EXISTS devices(id SERIAL PRIMARY KEY,serial_number TEXT UNIQUE NOT NULL,asset_code TEXT UNIQUE NOT NULL,brand TEXT NOT NULL,model TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'available',purchase_date DATE,note TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,full_name TEXT NOT NULL,type TEXT DEFAULT 'student',class_or_department TEXT,email TEXT,phone TEXT,device_id INT REFERENCES devices(id) ON DELETE SET NULL,borrow_date DATE,return_due_date DATE,return_reason TEXT,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS repairs(id SERIAL PRIMARY KEY,device_id INT REFERENCES devices(id) ON DELETE CASCADE,reporter_name TEXT NOT NULL,reporter_email TEXT,issue TEXT NOT NULL,details TEXT,status TEXT DEFAULT 'received',technician TEXT,opened_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),completed_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS admin_users(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'admin',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,admin_id INT REFERENCES admin_users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS audit_log(id SERIAL PRIMARY KEY,admin_id INT,action TEXT,entity TEXT,entity_id TEXT,detail TEXT,created_at TIMESTAMPTZ DEFAULT NOW());ALTER TABLE devices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();ALTER TABLE repairs ADD COLUMN IF NOT EXISTS details TEXT;ALTER TABLE repairs ADD COLUMN IF NOT EXISTS technician TEXT;ALTER TABLE repairs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();ALTER TABLE repairs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'admin';ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;`);const username=process.env.ADMIN_USERNAME||'admin';const password=process.env.ADMIN_PASSWORD;if(!password)throw new Error('ADMIN_PASSWORD is not configured in Vercel');await q(`INSERT INTO admin_users(username,password_hash,role,active) VALUES($1,$2,'admin',TRUE) ON CONFLICT(username) DO UPDATE SET password_hash=EXCLUDED.password_hash,role='admin',active=TRUE`,[username,makeHash(password)]);return true;})();return initialized;}
async function session(req){let token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token){const m=(req.headers.cookie||'').match(/(?:^|;\s*)jmw_session=([^;]+)/);token=m?.[1];}if(!token)return null;return one('SELECT s.*,a.username,a.role FROM sessions s JOIN admin_users a ON a.id=s.admin_id WHERE s.token_hash=$1 AND s.expires_at>NOW() AND a.active=TRUE',[sha(token)])}
async function auth(req,res,next){try{await init();req.s=await session(req);if(!req.s)return res.status(401).json({error:'กรุณาเข้าสู่ระบบ'});next()}catch(e){next(e)}}
async function audit(req,action,entity,id,detail=''){await q('INSERT INTO audit_log(admin_id,action,entity,entity_id,detail) VALUES($1,$2,$3,$4,$5)',[req.s?.admin_id||null,action,entity,String(id??''),detail])}
function classYears(v){const t=String(v||'').replace(/\s/g,'');if(/ม\.?4(?:\/|$)/.test(t))return 3;if(/ม\.?5(?:\/|$)/.test(t))return 2;if(/ม\.?6(?:\/|$)/.test(t))return 1;return null}
function addYears(dateValue,years){if(!dateValue||!years)return dateValue;const d=new Date(String(dateValue).slice(0,10)+'T00:00:00');const day=d.getDate();d.setFullYear(d.getFullYear()+years);if(d.getDate()!==day)d.setDate(0);return d.toISOString().slice(0,10)}
const statusLabels={received:'รับเรื่องแล้ว',checking:'กำลังตรวจสอบ',waiting_parts:'รออะไหล่',repairing:'กำลังซ่อม',completed:'ซ่อมเสร็จแล้ว',cancelled:'ยกเลิก'};
const dateOnly=v=>{const s=String(v??'');const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:s};
app.get('/api/public/devices',async(req,res,next)=>{try{await init();res.json((await q("SELECT id,serial_number,asset_code,brand,model,status FROM devices WHERE status <> 'retired' ORDER BY asset_code")).rows)}catch(e){next(e)}});
app.post('/api/public/repairs',async(req,res,next)=>{try{await init();const x=req.body||{};if(!x.device_id||!x.reporter_name||!x.issue)return res.status(400).json({error:'กรุณากรอกข้อมูลที่จำเป็นให้ครบ'});const device=await one("SELECT id,serial_number,asset_code,status FROM devices WHERE id=$1 AND status <> 'retired'",[Number(x.device_id)]);if(!device)return res.status(404).json({error:'ไม่พบเครื่อง Chromebook'});const r=await q('INSERT INTO repairs(device_id,reporter_name,reporter_email,issue,details,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,opened_at,reporter_name,reporter_email,issue,details',[Number(x.device_id),String(x.reporter_name).trim(),x.reporter_email||null,String(x.issue).trim(),x.details||null,'received']);await q("UPDATE devices SET status='repair',updated_at=NOW() WHERE id=$1",[Number(x.device_id)]);const email=await sendNewRepairEmail(r.rows[0],device);res.status(201).json({ok:true,message:'แจ้งซ่อมเรียบร้อยแล้ว',repair:r.rows[0],emailSent:email.sent,emailError:email.sent?null:email.error})}catch(e){next(e)}});
app.get('/api/public/repairs/:id',async(req,res,next)=>{try{await init();const id=Number(req.params.id);const email=String(req.query?.email||'').trim().toLowerCase();if(!Number.isInteger(id)||id<1||!email)return res.status(400).json({error:'กรุณาระบุเลขที่แจ้งซ่อมและอีเมล'});const row=await one(`SELECT r.id,r.status,r.opened_at,r.updated_at,r.completed_at,r.reporter_name,r.reporter_email,r.issue,r.details,r.technician,d.serial_number,d.asset_code FROM repairs r JOIN devices d ON d.id=r.device_id WHERE r.id=$1 AND LOWER(COALESCE(r.reporter_email,''))=$2`,[id,email]);if(!row)return res.status(404).json({error:'ไม่พบรายการแจ้งซ่อม หรืออีเมลไม่ตรงกับข้อมูลที่แจ้งไว้'});res.setHeader('Cache-Control','no-store,max-age=0');res.json({ok:true,repair:{...row,opened_at:dateOnly(row.opened_at),updated_at:dateOnly(row.updated_at),completed_at:dateOnly(row.completed_at),status_label:statusLabels[row.status]||row.status}})}catch(e){next(e)}});
app.get('/api/health',async(req,res)=>{try{await init();await q('SELECT 1');res.json({ok:true,database:true,environment:{admin:!!process.env.ADMIN_PASSWORD,smtp:!!process.env.SMTP_HOST,emailRecipient:!!adminMail}})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/auth/login',async(req,res,next)=>{try{await init();const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');const a=await one('SELECT * FROM admin_users WHERE username=$1 AND active=TRUE',[username]);if(!a||!verify(password,a.password_hash))return res.status(401).json({error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'});const token=crypto.randomBytes(32).toString('hex');await q("INSERT INTO sessions(token_hash,admin_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '12 hours')",[sha(token),a.id]);res.setHeader('Set-Cookie',`jmw_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`);res.json({ok:true,token,user:{id:a.id,username:a.username,role:a.role}})}catch(e){next(e)}});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:{id:req.s.admin_id,username:req.s.username,role:req.s.role}}));
app.post('/api/auth/logout',auth,async(req,res,next)=>{try{const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');await q('DELETE FROM sessions WHERE token_hash=$1',[sha(token)]);res.setHeader('Set-Cookie','jmw_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');res.json({ok:true})}catch(e){next(e)}});
app.get('/api/dashboard',auth,async(req,res,next)=>{try{const count=async(sql)=>Number((await one(sql)).c);res.json({total:await count('SELECT COUNT(*) c FROM devices'),available:await count("SELECT COUNT(*) c FROM devices WHERE status='available'"),assigned:await count("SELECT COUNT(*) c FROM devices WHERE status='assigned'"),repair:await count("SELECT COUNT(*) c FROM devices WHERE status='repair'"),retired:await count("SELECT COUNT(*) c FROM devices WHERE status='retired'"),overdue:await count("SELECT COUNT(*) c FROM users WHERE active=TRUE AND return_due_date<CURRENT_DATE"),repairsOpen:await count("SELECT COUNT(*) c FROM repairs WHERE status NOT IN ('completed','cancelled')")})}catch(e){next(e)}});
app.get('/api/devices',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM devices ORDER BY id DESC')).rows)}catch(e){next(e)}});
app.post('/api/devices',auth,async(req,res,next)=>{try{const x=req.body||{};if(!x.serial_number||!x.asset_code||!x.brand||!x.model)return res.status(400).json({error:'กรุณากรอก S/N, รหัสเครื่อง, ยี่ห้อ และรุ่นให้ครบ'});const r=await q('INSERT INTO devices(serial_number,asset_code,brand,model,purchase_date,status,note) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[x.serial_number,x.asset_code,x.brand,x.model,x.purchase_date||null,x.status||'available',x.note||null]);await audit(req,'create','device',r.rows[0].id,x.asset_code);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/devices/:id',auth,async(req,res,next)=>{try{const x=req.body||{};const r=await q('UPDATE devices SET serial_number=$1,asset_code=$2,brand=$3,model=$4,purchase_date=$5,status=$6,note=$7,updated_at=NOW() WHERE id=$8 RETURNING *',[x.serial_number,x.asset_code,x.brand,x.model,x.purchase_date||null,x.status||'available',x.note||null,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'ไม่พบอุปกรณ์'});await audit(req,'update','device',req.params.id,x.asset_code);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/devices/:id',auth,async(req,res,next)=>{try{const u=await one('SELECT id FROM users WHERE active=TRUE AND device_id=$1',[req.params.id]);if(u)return res.status(409).json({error:'อุปกรณ์ยังถูกยืมใช้งานอยู่'});await q('DELETE FROM devices WHERE id=$1',[req.params.id]);await audit(req,'delete','device',req.params.id);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/users',auth,async(req,res,next)=>{try{res.json((await q('SELECT u.*,d.asset_code,d.serial_number,d.brand,d.model FROM users u LEFT JOIN devices d ON d.id=u.device_id ORDER BY u.id DESC')).rows)}catch(e){next(e)}});
app.post('/api/users',auth,async(req,res,next)=>{try{const x=req.body||{};if(!x.full_name)return res.status(400).json({error:'กรุณาระบุชื่อผู้ใช้'});const years=classYears(x.class_or_department);const due=years&&x.borrow_date?addYears(x.borrow_date,years):(x.return_due_date||null);const r=await q('INSERT INTO users(full_name,type,class_or_department,email,phone,device_id,borrow_date,return_due_date,return_reason,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[x.full_name,x.type||'student',x.class_or_department||null,x.email||null,x.phone||null,x.device_id||null,x.borrow_date||null,due,x.return_reason||null,x.active!==false]);if(x.device_id&&x.active!==false)await q("UPDATE devices SET status='assigned',updated_at=NOW() WHERE id=$1 AND status NOT IN ('repair','retired')",[x.device_id]);await audit(req,'create','user',r.rows[0].id,x.full_name);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/users/:id',auth,async(req,res,next)=>{try{const x=req.body||{};const years=classYears(x.class_or_department);const due=years&&x.borrow_date?addYears(x.borrow_date,years):(x.return_due_date||null);const old=await one('SELECT * FROM users WHERE id=$1',[req.params.id]);if(!old)return res.status(404).json({error:'ไม่พบผู้ใช้'});const r=await q('UPDATE users SET full_name=$1,type=$2,class_or_department=$3,email=$4,phone=$5,device_id=$6,borrow_date=$7,return_due_date=$8,return_reason=$9,active=$10,updated_at=NOW() WHERE id=$11 RETURNING *',[x.full_name,x.type||old.type,x.class_or_department||null,x.email||null,x.phone||null,x.device_id||null,x.borrow_date||null,due,x.return_reason||null,x.active!==false,req.params.id]);if(x.device_id&&x.active!==false)await q("UPDATE devices SET status='assigned',updated_at=NOW() WHERE id=$1 AND status NOT IN ('repair','retired')",[x.device_id]);if(old.device_id&&old.device_id!==x.device_id)await q("UPDATE devices SET status='available',updated_at=NOW() WHERE id=$1 AND status='assigned'",[old.device_id]);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/users/:id',auth,async(req,res,next)=>{try{const old=await one('SELECT * FROM users WHERE id=$1',[req.params.id]);if(!old)return res.status(404).json({error:'ไม่พบผู้ใช้'});const client=await pool.connect();try{await client.query('BEGIN');if(old.device_id)await client.query("UPDATE devices SET status='available',updated_at=NOW() WHERE id=$1 AND status='assigned'",[old.device_id]);await client.query('DELETE FROM users WHERE id=$1',[req.params.id]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}await audit(req,'delete','user',req.params.id,old.full_name);res.json({ok:true,deleted:true})}catch(e){next(e)}});
app.get('/api/repairs',auth,async(req,res,next)=>{try{res.json((await q('SELECT r.*,d.asset_code,d.serial_number,d.brand,d.model FROM repairs r JOIN devices d ON d.id=r.device_id ORDER BY r.id DESC')).rows)}catch(e){next(e)}});
app.post('/api/repairs',auth,async(req,res,next)=>{try{const x=req.body||{};const r=await q('INSERT INTO repairs(device_id,reporter_name,reporter_email,issue,details,status,technician) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[x.device_id,x.reporter_name,x.reporter_email||null,x.issue,x.details||null,x.status||'received',x.technician||null]);await q("UPDATE devices SET status='repair',updated_at=NOW() WHERE id=$1",[x.device_id]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/repairs/:id',auth,async(req,res,next)=>{try{const x=req.body||{};const old=await one('SELECT * FROM repairs WHERE id=$1',[req.params.id]);if(!old)return res.status(404).json({error:'ไม่พบรายการแจ้งซ่อม'});const done=['completed','cancelled'].includes(x.status);const r=await q('UPDATE repairs SET status=$1,technician=$2,details=$3,updated_at=NOW(),completed_at=$4 WHERE id=$5 RETURNING *',[x.status||old.status,x.technician||old.technician,x.details??old.details,done?new Date():null,req.params.id]);await q("UPDATE devices SET status=$1,updated_at=NOW() WHERE id=$2",[done?'available':'repair',old.device_id]);await audit(req,'update','repair',req.params.id,x.status||old.status);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/audit',auth,async(req,res,next)=>{try{res.json((await q('SELECT l.*,a.username FROM audit_log l LEFT JOIN admin_users a ON a.id=l.admin_id ORDER BY l.id DESC LIMIT 200')).rows)}catch(e){next(e)}});
app.get('/api/cron/reminders',async(req,res)=>{if(process.env.CRON_SECRET&&req.headers.authorization!==`Bearer ${process.env.CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'});res.json({ok:true})});
app.use(express.static(path.join(__dirname,'public')));app.get('*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.use((err,req,res,next)=>{console.error('[JMW]',err);res.status(500).json({error:err.message||'เกิดข้อผิดพลาดภายในระบบ'})});
if(!process.env.VERCEL){init().then(()=>app.listen(Number(process.env.PORT||3000))).catch(e=>{console.error(e);process.exit(1)})}
export default app;
