import { Pool } from 'pg';
import crypto from 'crypto';
const url=process.env.DATABASE_URL;const pool=url?new Pool({connectionString:url,ssl:!url.includes('localhost')?{rejectUnauthorized:false}:undefined,max:2}):null;
const sha=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
const clean=v=>String(v??'').trim();
const key=v=>clean(v).toLowerCase().replace(/\s+/g,'').replace(/[\u200b\ufeff]/g,'');
const val=(row,names)=>{const wanted=names.map(key);const e=Object.entries(row||{}).find(([h])=>wanted.includes(key(h)));return e?e[1]:''};
const date=v=>{if(!v)return null;if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);if(typeof v==='number'){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=clean(v),m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})$/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null};
const years=v=>{const t=clean(v).replace(/\s/g,'');if(/ม\.?4(?:\/|$)/.test(t))return 3;if(/ม\.?5(?:\/|$)/.test(t))return 2;if(/ม\.?6(?:\/|$)/.test(t))return 1;return null};
const addYears=(s,y)=>{if(!s||!y)return s;const d=new Date(s+'T00:00:00'),day=d.getDate();d.setFullYear(d.getFullYear()+y);if(d.getDate()!=day)d.setDate(0);return d.toISOString().slice(0,10)};
async function auth(req,res){let t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t){const m=(req.headers.cookie||'').match(/(?:^|;\s*)jmw_session=([^;]+)/);t=m?.[1]}if(!t){res.status(401).json({error:'กรุณาเข้าสู่ระบบ'});return null}const s=(await pool.query('SELECT s.*,a.username FROM sessions s JOIN admin_users a ON a.id=s.admin_id WHERE s.token_hash=$1 AND s.expires_at>NOW() AND a.active=TRUE',[sha(t)])).rows[0];if(!s){res.status(401).json({error:'กรุณาเข้าสู่ระบบ'});return null}return s}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method Not Allowed'});try{if(!pool)throw Error('DATABASE_URL is not configured');const admin=await auth(req,res);if(!admin)return;const {devices=[],users=[]}=req.body||{};if(!Array.isArray(devices)||!Array.isArray(users))return res.status(400).json({error:'รูปแบบข้อมูล Excel ไม่ถูกต้อง'});if(devices.length+users.length>5000)return res.status(400).json({error:'ข้อมูลเกิน 5,000 รายการต่อครั้ง'});
const c=await pool.connect();let ni=0,nu=0,di=0,du=0,sk=[];try{await c.query('BEGIN');
for(const r of devices){const sn=clean(val(r,['S/N','SN','Serial Number','serial_number'])),ac=clean(val(r,['รหัสเครื่อง','Asset Code','asset_code'])),br=clean(val(r,['ยี่ห้อ','Brand','brand'])),mo=clean(val(r,['รุ่น','Model','model']));if(!sn&&!ac&&!br&&!mo)continue;if(!sn||!ac||!br||!mo){sk.push('อุปกรณ์: ข้อมูลไม่ครบ');continue}const sm={'พร้อมใช้งาน':'available','กำลังใช้งาน':'assigned','กำลังซ่อม':'repair','เลิกใช้':'retired'},rs=clean(val(r,['สถานะ','Status','status'])),st=sm[rs]||(['available','assigned','repair','retired'].includes(rs)?rs:'available'),pd=date(val(r,['วันที่ซื้อ','Purchase Date','purchase_date'])),note=clean(val(r,['หมายเหตุ','Note','note']))||null;const ex=(await c.query('SELECT id FROM devices WHERE serial_number=$1 OR asset_code=$2 LIMIT 1',[sn,ac])).rows[0];if(ex){await c.query('UPDATE devices SET serial_number=$1,asset_code=$2,brand=$3,model=$4,status=$5,purchase_date=$6,note=$7,updated_at=NOW() WHERE id=$8',[sn,ac,br,mo,st,pd,note,ex.id]);du++}else{await c.query('INSERT INTO devices(serial_number,asset_code,brand,model,status,purchase_date,note) VALUES($1,$2,$3,$4,$5,$6,$7)',[sn,ac,br,mo,st,pd,note]);di++}}
const deviceMap=new Map();const all=(await c.query('SELECT id,serial_number,asset_code FROM devices')).rows;all.forEach(d=>{if(d.serial_number)deviceMap.set(key(d.serial_number),d.id);if(d.asset_code)deviceMap.set(key(d.asset_code),d.id)});
for(const r of users){const name=clean(val(r,['ชื่อผู้ใช้เครื่อง','ชื่อผู้ใช้','Full Name','full_name'])),cl=clean(val(r,['ระดับชั้น/ฝ่ายงาน','ระดับชั้น','Class/Department','class_or_department'])),email=clean(val(r,['อีเมล','Email','email']))||null,phone=clean(val(r,['เบอร์โทร','โทรศัพท์','Phone','phone']))||null,sn=clean(val(r,['S/N','SN','Serial Number','serial_number'])),ac=clean(val(r,['รหัสเครื่อง','Asset Code','asset_code'])),bd=date(val(r,['วันที่ยืม','Borrow Date','borrow_date'])),manual=date(val(r,['วันที่ต้องคืน','Return Due Date','return_due_date'])),yr=years(cl),due=bd&&yr?addYears(bd,yr):manual,reason=clean(val(r,['เหตุผลคืน','Return Reason','return_reason']))||null,type=clean(val(r,['ประเภท','Type','type']))||'student';if(!name)continue;const did=deviceMap.get(key(sn))||deviceMap.get(key(ac))||null;if((sn||ac)&&!did)sk.push(`ผู้ใช้ ${name}: ไม่พบเครื่อง ${sn||ac}`);const ex=email?(await c.query('SELECT id FROM users WHERE LOWER(email)=LOWER($1) LIMIT 1',[email])).rows[0]:null;if(ex){await c.query('UPDATE users SET full_name=$1,type=$2,class_or_department=$3,email=$4,phone=$5,device_id=$6,borrow_date=$7,return_due_date=$8,return_reason=$9,active=TRUE,updated_at=NOW() WHERE id=$10',[name,type,cl,email,phone,did,bd,due,reason,ex.id]);nu++}else{await c.query('INSERT INTO users(full_name,type,class_or_department,email,phone,device_id,borrow_date,return_due_date,return_reason,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,TRUE)',[name,type,cl,email,phone,did,bd,due,reason]);ni++}if(did)await c.query("UPDATE devices SET status='assigned',updated_at=NOW() WHERE id=$1 AND status NOT IN ('repair','retired')",[did])}
await c.query('INSERT INTO audit_log(admin_id,action,entity,detail) VALUES($1,$2,$3,$4)',[admin.admin_id,'import','excel',`devices:${di+du}, users:${ni+nu}`]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
res.json({ok:true,message:`นำเข้าสำเร็จ อุปกรณ์ใหม่ ${di} / แก้ไข ${du} / ผู้ใช้ใหม่ ${ni} / แก้ไข ${nu}`,skipped:sk.slice(0,100)})}catch(e){console.error('[IMPORT JSON]',e);res.status(500).json({error:e.message||'นำเข้าไม่สำเร็จ'})}}